
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class Document
{

    public Document()
    {

        this.CurrentSteps = new HashSet<CurrentStep>();

        this.Steps = new HashSet<Step>();

    }


    public int Id { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Text { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> TypeId { get; set; }

    public System.DateTime DateTime { get; set; }



    public virtual ICollection<CurrentStep> CurrentSteps { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<Step> Steps { get; set; }

}

}
