
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class DocumentType
{

    public DocumentType()
    {

        this.Documents = new HashSet<Document>();

        this.DocumentTemplates = new HashSet<DocumentTemplate>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Document> Documents { get; set; }

    public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }

}

}
