
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class Step
{

    public Step()
    {

        this.CurrentSteps = new HashSet<CurrentStep>();

    }


    public int Id { get; set; }

    public int DocumentId { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<bool> Status { get; set; }

    public int SerialNumber { get; set; }



    public virtual ICollection<CurrentStep> CurrentSteps { get; set; }

    public virtual Document Document { get; set; }

    public virtual User User { get; set; }

}

}
