
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.CurrentSteps = new HashSet<CurrentStep>();

        this.Documents = new HashSet<Document>();

        this.Steps = new HashSet<Step>();

    }


    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Patronymic { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string UserName { get; set; }

    public int PositionId { get; set; }

    public Nullable<int> RoleId { get; set; }



    public virtual ICollection<CurrentStep> CurrentSteps { get; set; }

    public virtual ICollection<Document> Documents { get; set; }

    public virtual Position Position { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<Step> Steps { get; set; }

}

}
